ds:
   sell:
        url: jdbc:jtds:sqlserver://127.0.0.1/Sell
        driverClassName: net.sourceforge.jtds.jdbc.Driver
        username: sa
        password: 123456
   bank:
        url: jdbc:mysql://127.0.0.1:3306/bank?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123456
        #连接池的配置信息
        initialSize: 10
        minIdle: 10
        maxActive: 100
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver

server:
  port: 9001
spring:
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/bank
    username: root
    password: 123456
  session:
    store-type: jdbc
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.tuandai.model
  config-location: classpath:mybatis-config.xml    #一定要注明location的位置
  # default-store in spring session. it will be set in redis only outside.
rabbit:
  connect:
    host: localhost
    port: 5672
    username: admin
    password: 123456
    channelCacheSize: 100